-- CMS database schema
-- Generated by: php database/migrate.php export
-- Single source of truth. Apply with: php database/migrate.php init
-- To change the schema, change the live DB then re-run `export`.

PRAGMA foreign_keys = ON;

CREATE TABLE ai_runs (
  id              INTEGER PRIMARY KEY AUTOINCREMENT,
  job_id          INTEGER REFERENCES jobs(id) ON DELETE SET NULL,
  prompt_id       INTEGER REFERENCES prompts(id),
  prompt_version  INTEGER,
  stage           TEXT,
  provider        TEXT NOT NULL CHECK (provider IN ('kilo','zen')),
  model           TEXT NOT NULL,
  input_tokens    INTEGER NOT NULL DEFAULT 0,
  output_tokens   INTEGER NOT NULL DEFAULT 0,
  cost_usd        REAL NOT NULL DEFAULT 0,
  latency_ms      INTEGER,
  status          TEXT NOT NULL CHECK (status IN ('ok','error','fallback','rate_limited')),
  http_status     INTEGER,
  error           TEXT,
  input_hash      TEXT,                      -- dedupe identical generations
  ref             TEXT,                      -- resulting entity (post:123)
  created_at      TEXT NOT NULL DEFAULT (datetime('now'))
);

-- One row per manual agent invocation from the admin UI.
--
-- Deliberately NOT part of ai_runs: that table is a per-LLM-call token/cost
-- ledger keyed on provider+model, and it has no notion of "which agent" or
-- "which human asked". Recording an agent run in it would conflate a spend
-- record with an activity record, and the /admin/agents screen needs both.
CREATE TABLE agent_runs (
  id           INTEGER PRIMARY KEY AUTOINCREMENT,
  agent        TEXT NOT NULL,
  status       TEXT NOT NULL CHECK (status IN ('ok','failed','unknown')),
  duration_ms  INTEGER NOT NULL DEFAULT 0,
  error        TEXT,
  user_id      INTEGER REFERENCES users(id) ON DELETE SET NULL,
  created_at   TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX idx_agent_runs_created ON agent_runs(created_at DESC);
CREATE INDEX idx_agent_runs_agent   ON agent_runs(agent);

CREATE TABLE audit_log (
  id         INTEGER PRIMARY KEY AUTOINCREMENT,
  actor_id   INTEGER REFERENCES users(id),
  action     TEXT NOT NULL,                  -- post.publish, settings.update
  entity     TEXT,
  entity_id  TEXT,
  before_json TEXT,
  after_json  TEXT,
  ip_hash    TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE categories (
  id          INTEGER PRIMARY KEY AUTOINCREMENT,
  slug        TEXT NOT NULL UNIQUE,
  name        TEXT NOT NULL,
  description TEXT,
  parent_id   INTEGER REFERENCES categories(id),
  sort_order  INTEGER NOT NULL DEFAULT 0,
  created_at  TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE comments (
  id          INTEGER PRIMARY KEY AUTOINCREMENT,
  post_id     INTEGER NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
  parent_id   INTEGER REFERENCES comments(id) ON DELETE CASCADE,
  author_name TEXT NOT NULL,
  author_email_hash TEXT,
  body_md     TEXT NOT NULL,
  status      TEXT NOT NULL DEFAULT 'pending'
              CHECK (status IN ('pending','approved','spam','trash')),
  ip_hash     TEXT,
  created_at  TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE cron_runs (
  id           INTEGER PRIMARY KEY AUTOINCREMENT,
  cron_key     TEXT NOT NULL,                -- daily_blog, sitemap_ping, seo_audit
  scheduled_for TEXT NOT NULL,               -- intended slot (UTC)
  job_id       INTEGER REFERENCES jobs(id),
  status       TEXT NOT NULL CHECK (status IN ('ok','failed','skipped','running')),
  detail       TEXT,
  started_at   TEXT NOT NULL DEFAULT (datetime('now')),
  finished_at  TEXT,
  UNIQUE (cron_key, scheduled_for)           -- idempotent: never double-post
);

CREATE TABLE design_tokens (
  key      TEXT PRIMARY KEY,                 -- color.primary, font.heading, space.md
  value    TEXT NOT NULL,
  category TEXT NOT NULL CHECK (category IN
            ('color','font','space','radius','shadow','layout')),
  css_var  TEXT NOT NULL,                    -- --color-primary
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE job_logs (
  id         INTEGER PRIMARY KEY AUTOINCREMENT,
  job_id     INTEGER NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
  level      TEXT NOT NULL DEFAULT 'info' CHECK (level IN ('debug','info','warn','error')),
  message    TEXT NOT NULL,
  context    TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE jobs (
  id              INTEGER PRIMARY KEY AUTOINCREMENT,
  type            TEXT NOT NULL,            -- generate_daily_post, render_site, seo_score, ...
  payload         TEXT NOT NULL DEFAULT '{}',
  status          TEXT NOT NULL DEFAULT 'queued'
                  CHECK (status IN ('queued','running','succeeded','failed','dead','cancelled')),
  priority        INTEGER NOT NULL DEFAULT 100,  -- lower runs first
  run_after       TEXT NOT NULL DEFAULT (datetime('now')),
  attempts        INTEGER NOT NULL DEFAULT 0,
  max_attempts    INTEGER NOT NULL DEFAULT 3,
  locked_by       TEXT,                      -- worker id / runner id
  locked_at       TEXT,
  idempotency_key TEXT UNIQUE,               -- prevents duplicate cron/AI jobs
  last_error      TEXT,
  result          TEXT,
  created_by      INTEGER REFERENCES users(id),
  created_at      TEXT NOT NULL DEFAULT (datetime('now')),
  started_at      TEXT,
  finished_at     TEXT
);

CREATE TABLE media (
  id           INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid         TEXT NOT NULL UNIQUE,
  storage      TEXT NOT NULL DEFAULT 'r2' CHECK (storage IN ('r2','remote')),
  key          TEXT NOT NULL,                -- R2 object key
  url          TEXT NOT NULL,                -- public URL (R2 public / custom domain)
  mime         TEXT NOT NULL,
  bytes        INTEGER NOT NULL,
  width        INTEGER,
  height       INTEGER,
  alt          TEXT,
  caption      TEXT,
  checksum     TEXT,
  uploaded_by  INTEGER REFERENCES users(id),
  created_at   TEXT NOT NULL DEFAULT (datetime('now')),
  UNIQUE (storage, key)
);

CREATE TABLE post_categories (
  post_id     INTEGER NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
  category_id INTEGER NOT NULL REFERENCES categories(id) ON DELETE CASCADE,
  PRIMARY KEY (post_id, category_id)
);

CREATE TABLE post_tags (
  post_id INTEGER NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
  tag_id  INTEGER NOT NULL REFERENCES tags(id)  ON DELETE CASCADE,
  PRIMARY KEY (post_id, tag_id)
);

CREATE TABLE posts (
  id              INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid            TEXT NOT NULL UNIQUE,
  slug            TEXT NOT NULL,
  type            TEXT NOT NULL DEFAULT 'post'
                  CHECK (type IN ('post','page')),
  title           TEXT NOT NULL,
  excerpt         TEXT,
  body_md         TEXT,                      -- canonical source (markdown + front-matter blocks)
  body_html       TEXT,                      -- rendered cache
  status          TEXT NOT NULL DEFAULT 'draft'
                  CHECK (status IN ('draft','review','published','scheduled','trash')),
  author_id       INTEGER REFERENCES users(id),
  featured_media_id INTEGER,
  template        TEXT,                      -- theme layout override
  menu_order      INTEGER NOT NULL DEFAULT 0,
  allow_comments  INTEGER NOT NULL DEFAULT 1,
  revision        INTEGER NOT NULL DEFAULT 0,
  word_count      INTEGER NOT NULL DEFAULT 0,
  reading_time    INTEGER NOT NULL DEFAULT 0,
  origin          TEXT NOT NULL DEFAULT 'manual'  -- manual | ai | ai_edited
                  CHECK (origin IN ('manual','ai','ai_edited')),
  created_at      TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at      TEXT NOT NULL DEFAULT (datetime('now')),
  published_at    TEXT,
  scheduled_at    TEXT
);

CREATE VIRTUAL TABLE posts_fts USING fts5(
            title, excerpt, body_md,
            content=posts, content_rowid=id, tokenize='porter unicode61'
        );

CREATE TABLE prompt_versions (
  id         INTEGER PRIMARY KEY AUTOINCREMENT,
  prompt_id  INTEGER NOT NULL REFERENCES prompts(id) ON DELETE CASCADE,
  version    INTEGER NOT NULL,
  template   TEXT NOT NULL,
  model      TEXT,
  temperature REAL,
  changelog  TEXT,
  created_by INTEGER REFERENCES users(id),
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  UNIQUE (prompt_id, version)
);

CREATE TABLE prompts (
  id            INTEGER PRIMARY KEY AUTOINCREMENT,
  slug          TEXT NOT NULL UNIQUE,        -- daily_post, title_optimize, seo_pack ...
  name          TEXT NOT NULL,
  stage         TEXT NOT NULL CHECK (stage IN
                ('research','draft','rewrite','edit','title','excerpt','seo','social','image')),
  template      TEXT NOT NULL,               -- {{placeholders}} filled at run time
  provider      TEXT NOT NULL DEFAULT 'kilo' CHECK (provider IN ('kilo','zen','auto')),
  model         TEXT,                        -- NULL = provider default
  temperature   REAL NOT NULL DEFAULT 0.7,
  max_tokens    INTEGER NOT NULL DEFAULT 4096,
  output_format TEXT NOT NULL DEFAULT 'text'
                CHECK (output_format IN ('text','json','markdown')),
  is_active     INTEGER NOT NULL DEFAULT 1,
  created_at    TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at    TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE redirects (
  id          INTEGER PRIMARY KEY AUTOINCREMENT,
  source_path TEXT NOT NULL UNIQUE,
  target_path TEXT NOT NULL,
  status_code INTEGER NOT NULL DEFAULT 301 CHECK (status_code IN (301,302,307,308)),
  hits        INTEGER NOT NULL DEFAULT 0,
  created_at  TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE revisions (
  id             INTEGER PRIMARY KEY AUTOINCREMENT,
  post_id        INTEGER NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
  revision       INTEGER NOT NULL,
  editor_id      INTEGER REFERENCES users(id),
  title          TEXT NOT NULL,
  excerpt        TEXT,
  body_md        TEXT NOT NULL,
  change_summary TEXT,
  tokens_used    INTEGER,
  created_at     TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE seo_meta (
  entity_type     TEXT NOT NULL CHECK (entity_type IN ('post','page','category','tag','home')),
  entity_id       TEXT NOT NULL,
  meta_title      TEXT,
  meta_description TEXT,
  canonical_url   TEXT,
  og_image_media_id INTEGER,
  robots          TEXT NOT NULL DEFAULT 'index,follow',
  focus_keyword   TEXT,
  schema_json     TEXT,                      -- JSON-LD block
  score           INTEGER,                   -- 0-100 audit score
  checked_at      TEXT,
  updated_at      TEXT NOT NULL DEFAULT (datetime('now')),
  PRIMARY KEY (entity_type, entity_id)
);

CREATE TABLE sessions (
  id           TEXT PRIMARY KEY,            -- sha256(token), raw token only in cookie
  user_id      INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  ip_hash      TEXT,
  user_agent   TEXT,
  csrf_token   TEXT NOT NULL,
  created_at   TEXT NOT NULL DEFAULT (datetime('now')),
  last_seen_at TEXT NOT NULL DEFAULT (datetime('now')),
  expires_at   TEXT NOT NULL
);

CREATE TABLE settings (
  key        TEXT PRIMARY KEY,              -- site.title, site.url, ai.provider, ...
  value      TEXT NOT NULL,                 -- JSON-encoded
  scope      TEXT NOT NULL DEFAULT 'general',
  is_public  INTEGER NOT NULL DEFAULT 0,    -- safe to expose to frontend
  updated_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_by INTEGER REFERENCES users(id)
);

CREATE TABLE tags (
  id          INTEGER PRIMARY KEY AUTOINCREMENT,
  slug        TEXT NOT NULL UNIQUE,
  name        TEXT NOT NULL,
  usage_count INTEGER NOT NULL DEFAULT 0,
  created_at  TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE themes (
  id          INTEGER PRIMARY KEY AUTOINCREMENT,
  slug        TEXT NOT NULL UNIQUE,
  name        TEXT NOT NULL,
  source      TEXT NOT NULL DEFAULT 'builtin' CHECK (source IN ('builtin','ai','imported')),
  config_json TEXT NOT NULL DEFAULT '{}',    -- layout slots, palette seed, font pairing
  is_active   INTEGER NOT NULL DEFAULT 0,
  created_at  TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE users (
  id              INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid            TEXT NOT NULL UNIQUE,
  email           TEXT NOT NULL UNIQUE,
  username        TEXT NOT NULL UNIQUE,
  password_hash   TEXT NOT NULL,             -- argon2id
  display_name    TEXT,
  role            TEXT NOT NULL DEFAULT 'author'
                  CHECK (role IN ('admin','editor','author')),
  avatar_media_id INTEGER,
  locale          TEXT NOT NULL DEFAULT 'en',
  status          TEXT NOT NULL DEFAULT 'active'
                  CHECK (status IN ('active','suspended')),
  failed_attempts INTEGER NOT NULL DEFAULT 0,
  locked_until    TEXT,
  last_login_at   TEXT,
  created_at      TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at      TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX idx_ai_runs_created ON ai_runs(created_at);

CREATE INDEX idx_ai_runs_status  ON ai_runs(status, created_at);

CREATE INDEX idx_audit_created ON audit_log(created_at);

CREATE INDEX idx_comments_post ON comments(post_id, status, created_at);

CREATE INDEX idx_job_logs_job ON job_logs(job_id, id);

CREATE INDEX idx_jobs_claim ON jobs(status, run_after, priority);

CREATE INDEX idx_jobs_type   ON jobs(type, status);

CREATE INDEX idx_post_tags_tag ON post_tags(tag_id);

CREATE INDEX idx_posts_author ON posts(author_id);

CREATE INDEX idx_posts_listing ON posts(type, status, published_at DESC);

CREATE INDEX idx_posts_slug ON posts(slug);

CREATE UNIQUE INDEX idx_posts_slug_type ON posts(type, slug);

CREATE INDEX idx_posts_status ON posts(status, published_at DESC);

CREATE INDEX idx_posts_type ON posts(type, status);

CREATE INDEX idx_revisions_post ON revisions(post_id, revision DESC);

CREATE INDEX idx_sessions_exp  ON sessions(expires_at);

CREATE INDEX idx_sessions_expiry ON sessions(expires_at);

CREATE INDEX idx_sessions_user ON sessions(user_id);

CREATE INDEX idx_users_email ON users(email);

CREATE INDEX idx_users_role ON users(role, status);
