<?php
/**
 * Seeder — creates the initial admin user and any baseline settings.
 *
 * Safe to re-run: every insert is idempotent (ON CONFLICT DO NOTHING).
 *
 * Usage:
 *   php database/seed.php [email] [password] [role]
 * Defaults: admin@cms.local / (random, printed to stdout) / admin
 */
declare(strict_types=1);

require_once __DIR__ . '/../vendor/autoload.php';

if (is_file(base_path('.env'))) {
    Dotenv\Dotenv::createImmutable(base_path())->safeLoad();
}

$db   = new \CMS\Database\Connection(require __DIR__ . '/../config/database.php');
$pdo  = $db->getPdo();
$auth = require __DIR__ . '/../config/auth.php';

$email = $argv[1] ?? 'admin@cms.local';
$role  = $argv[3] ?? 'admin';
$shown = false;

if (!in_array($role, ['admin', 'editor', 'author'], true)) {
    fwrite(STDERR, "role must be admin, editor or author\n");
    exit(1);
}

if (!isset($argv[2])) {
    // No password given — generate a strong one and print it once.
    $password = rtrim(strtr(base64_encode(random_bytes(12)), '+/', '-_'), '=');
    $shown = true;
} else {
    $password = $argv[2];
}

if (strlen($password) < 8) {
    fwrite(STDERR, "password must be at least 8 characters\n");
    exit(1);
}

$username = strstr($email, '@', true) ?: 'user';

$stmt = $pdo->prepare(
    'INSERT INTO users (uuid, email, username, password_hash, display_name, role, status)
     VALUES (?, ?, ?, ?, ?, ?, \'active\')
     ON CONFLICT(email) DO UPDATE SET
         password_hash = excluded.password_hash,
         role          = excluded.role,
         status        = \'active\',
         failed_attempts = 0,
         locked_until  = NULL'
);
$stmt->execute([
    bin2hex(random_bytes(16)),
    $email,
    $username,
    password_hash($password, $auth['password']['algo']),
    $username,
    $role,
]);

// Baseline settings the renderer and SEO agent read.
$seedSettings = [
    ['site_title',        'CMS Site',        'system'],
    ['site_description',  'Generated by AI', 'system'],
    ['posts_per_page',    '10',              'system'],
    ['default_post_status','draft',          'system'],
];

$set = $pdo->prepare(
    'INSERT INTO settings (key, value, scope) VALUES (?, ?, ?)
     ON CONFLICT(key) DO NOTHING'
);
foreach ($seedSettings as [$k, $v, $s]) {
    $set->execute([$k, json_encode($v), $s]);
}

echo "Seeded user: {$email} ({$role})\n";
if ($shown) {
    echo "Password:   {$password}\n";
    echo "  ^ generated once and never stored in plaintext — save it now.\n";
}